show databases;
create database Address_Book;
USE Address_Book;
CREATE TABLE AddressBook(
FIRSTNAME VARCHAR(50) NOT NULL,
LASTNAME VARCHAR(50) NOT NULL,
ADDRESS VARCHAR(100),
CITY VARCHAR(50),
STATE VARCHAR(50),
ZIP VARCHAR(10),
PHONENUMBER VARCHAR(10),
EMAIL VARCHAR(50));
DESC AddressBook;
INSERT INTO AddressBook(FIRSTNAME,LASTNAME,ADDRESS,CITY,STATE,ZIP,PHONENUMBER,EMAIL)
VALUES('PRASANTH','PALLE','NANDIKOTKUR','KURNOOL','ANDHRAPRADESH','518401','7598130306','palleprasnath@gmail.com'),
('RAHIMAN','ABDUL','NANDIKOTKUR','KURNOOL','ANDHRAPRADESH','518401','9703519040','iamrahiman@gmail.com'),
('MANSOOOR','BASHA','NANDIKOTKUR','KURNOOL','ANDHRAPRADESH','518401','7598130306','bmbndk2@gmail.com'),
('Jane', 'Doe', '456 Oak St', 'Anytown', 'CA', '12345', '555-6789', 'janedoe@email.com');

DROP TABLE AddressBook;
SELECT * FROM AddressBook;
UPDATE AddressBook
SET PHONENUMBER = '0000000000'
WHERE FIRSTNAME = "PRASANTH";

DELETE FROM AddressBook
WHERE FIRSTNAME = "PRASANTH";

SELECT *
FROM AddressBook
WHERE CITY = "KURNOOL" OR STATE = "ANDHRAPRADESH";

SELECT CITY, COUNT(*) AS COUNT
FROM AddressBook
GROUP BY CITY;

SELECT STATE, COUNT(*) AS COUNT
FROM AddressBook
GROUP BY STATE;

SELECT *
FROM AddressBook
WHERE CITY = "KURNOOL"
ORDER BY FIRSTNAME ASC;

ALTER TABLE AddressBook
ADD COLUMN BOOKNAME VARCHAR(50),
ADD COLUMN BOOKTYPE VARCHAR(50);

DESC AddressBook;

SELECT BOOKTYPE, COUNT(BOOKTYPE) AS COUNT
FROM AddressBook
GROUP BY BOOKTYPE;

SELECT *
FROM AddressBook;

INSERT INTO AddressBook(FIRSTNAME,LASTNAME,ADDRESS,CITY,STATE,ZIP,PHONENUMBER,EMAIL,BOOKNAME,BOOKTYPE)
VALUES ('John', 'Doe', '123 Main St', 'Anytown', 'CA', '12345', '5555551234', 'john.doe@example.com', 'Friend', 'Friend'),
('John', 'Doe', '123 Main St', 'Anytown', 'CA', '12345', '5555551234', 'john.doe@example.com', 'Family', 'Family');


